name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Get dependencies
      run: go install golang.org/x/exp/cmd/gorelease

    - name: Check
      run: $(go env GOPATH)/bin/gorelease
